name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up environment variables
      run: |
        echo "ES_ENDPOINT=${{ secrets.ES_ENDPOINT }}" >> $GITHUB_ENV
        echo "ES_CLOUDID=${{ secrets.ES_CLOUDID }}" >> $GITHUB_ENV
        echo "ES_API=${{ secrets.ES_API }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "MODEL_SETTINGS=${{ secrets.MODEL_SETTINGS }}" >> $GITHUB_ENV
        echo "SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}" >> $GITHUB_ENV
        echo "LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}" >> $GITHUB_ENV
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> $GITHUB_ENV
    - name: Verify environment variables
      run: env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt pytest
    - name: Discover tests
      run: pytest --collect-only app/
    - name: Test with pytest
      run: pytest app/

