name: Publish Docker Image

on:
  push:
    branches: ['main']  # Updated to 'main' as it's a common default branch name. Change if needed.

jobs:
  push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # Step 2: Log in to Docker Hub using token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set your username in repository secrets
          password: ${{ secrets.DOCKER_TOKEN }}     # Use Docker token instead of password
      
      # Step 3: Extract metadata for tagging and labeling the image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: owaisibnmushtaq/testapp  # Update the image name with your Docker Hub repo name
      
      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Directory containing the Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
