name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt pytest
    - name: Discover tests
      run: pytest --collect-only app/
    - name: Test with pytest
      env:
       REDIS_URL: ${{ secrets.REDIS_URL }}
       ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
       ES_CLOUDID: ${{ secrets.ES_CLOUDID }}
       ES_API: ${{ secrets.ES_API }}
       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
       MODEL_SETTINGS: '{model_name: gpt-3.5-turbo-1106, streaming: True }'
       SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
       LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }} 
      run: pytest app/
  
